### ISSUE TITLE
导航栏

### ISSUE THREAD

**Issue by guanpengchn** [guanpengchn/guanpengchn.github.io#79]
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title></title>
  </head>
  <body>
    <div class="navbar">
      <ul class="heading">
        <li>
          <a>下拉框</a>
          <ul>
            <li>1</li>
            <li>2</li>
            <li>3</li>
            <li>4</li>
            <li>5</li>
          </ul>
        </li>
      </ul>
    </div>
  </body>
</html>
```

```css
*{
  margin: 0px;
  padding: 0px;
}
.navbar {
  width: 100%;
  background: gray;
}
.heading>li{
  line-height: 40px;
  text-align: center;
  width: 60px;
  height: 40px;
  list-style: none;
  background-color:silver;
}
.heading>li>ul>li{
  display: none;
}
.heading>li:hover ul li {
  background: silver;
  display: block;
}
.heading>li>ul>li>a{
  text-decoration: none;
}
.heading>li>ul{
  display: block;
}
```

没有js
